name: actions-eslint
description: 🔨 Native, blazingly-fast ESlint CLI on Github Actions
branding:
  icon: align-justify
  color: red
inputs:
  args:
    description: ESlint CLI arguments
    required: true
runs:
  using: node12
  main: dist/index.js
