name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_VERSION: 16

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: eslint --version
        uses: ./
        with:
          args: --version
      - name: eslint --help
        uses: ./
        with:
          args: --help
      - name: eslint .
        uses: ./
        with:
          args: .
      - name: eslint --fix .
        uses: ./
        with:
          args: --fix .
  verify-output:
    name: Verify output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Rebuild output
        run: yarn build -o dist-ci
      - name: Verify output
        run: diff -qr dist dist-ci
